#pragma once

#include "packingsolver/rectangle/solution.hpp"

namespace packingsolver
{
namespace rectangle
{

/**
 * A block: a rectangular envelope filled with items in a guillotine pattern.
 *
 * Items are laid out relative to the block origin (0,0). The envelope is the
 * smallest axis-aligned rectangle enclosing all items. fill_rate = item_area /
 * rect.area().
 *
 * Generated by compute_blocks(); allocated in empty spaces during tree search.
 */
struct Block
{
    /** Envelope dimensions (bounding rectangle of all items in the block). */
    Rectangle rect = {0, 0};

    /** Sum of areas of all items inside the block. */
    Area item_area = 0;

    /** Sum of profits of all items inside the block. */
    Profit item_profit = 0;

    /**
     * Sum of weights of all items inside the block. compute_blocks() also
     * discards any block whose own weight already exceeds its bin type's
     * 'maximum_weight' (such a block could never be validly placed
     * regardless of anything else sharing the bin, since weight only ever
     * adds up) - see 'compute_blocks_for_bin' in 'block.cpp'.
     */
    Weight weight = 0;

    /**
     * Consumption of each resource of the block's own bin type, indexed by
     * resource_id, assuming the block is placed on its own (each item
     * type's copies starting at copy index 0 - see 'Resource::
     * item_consumptions'). Computed once by compute_blocks(), which also
     * discards any block whose consumption of a non-'penalize' resource
     * already exceeds that resource's capacity on its own (such a block
     * could never be validly placed regardless of anything else sharing
     * the bin, since consumption only ever adds up) - see
     * 'compute_blocks_for_bin' in 'block.cpp'. 'item_profit' is left
     * unadjusted (a plain, freely-additive sum of raw item profits): a
     * 'penalize' resource's penalty depends on what else shares the bin (see
     * 'BranchingSchemeMaximalSpaces::insertion_profit' in
     * 'tree_search_maximal_spaces.cpp'), which this block-local field alone
     * cannot capture. Empty iff the bin type has no resources.
     */
    std::vector<double> resource_consumption;

    bool is_simple = false;

    ItemTypeId item_type_id = -1;

    bool rotate = false;

    /**
     * Number of copies of each item type used in this block, as a sorted
     * sparse list of (item_type_id, count) pairs.  Only item types with at
     * least one copy are present.
     */
    std::vector<std::pair<ItemTypeId, ItemPos>> item_copies;

    /**
     * Items with their positions relative to the block's bottom-left corner
     * (origin).  Uses SolutionItem::bl_corner as the relative position.
     */
    std::vector<SolutionItem> items;

    ItemPos number_of_items = 0;

    double fill_rate() const { return (double)item_area / rect.area(); }

    double efficiency() const { return (double)item_profit / rect.area(); }
};

std::ostream& operator<<(std::ostream& os, const Block& block);

/**
 * Per-axis reachable-length tables.
 *
 * max_reachable_x[r] = largest length ≤ r achievable by stacking copies of
 * items (one rotation per copy, respecting copy limits) along x.  Computed
 * once from the instance and shared by compute_blocks and
 * BranchingSchemeMaximalSpaces.
 */
struct MaxReachableLengths
{
    std::vector<Length> x;
    std::vector<Length> y;
};

MaxReachableLengths compute_max_reachable_lengths(const Instance& instance);

/**
 * Parameters for compute_blocks().
 */
struct BlockParameters
{
    /** Maximum number of blocks to generate. */
    ItemPos maximum_number_of_blocks = 10000;
};

/**
 * Generate up to parameters.maximum_number_of_blocks guillotine blocks for
 * each bin type of the given instance.
 *
 * Returns one vector of blocks per bin type (indexed by BinTypeId).
 */
std::vector<std::vector<Block>> compute_blocks(
    const Instance& instance,
    const BlockParameters& parameters = {});

} // namespace rectangle
} // namespace packingsolver
