#pragma once

#include "packingsolver/rectangleguillotine/instance.hpp"

namespace packingsolver
{
namespace rectangleguillotine
{

/**
 * A block: a rectangular envelope filled with items in a guillotine pattern.
 *
 * Items are laid out relative to the block origin (0,0). The envelope is the
 * smallest axis-aligned rectangle enclosing all items.
 * fill_rate = item_area / rect.area().
 *
 * number_of_stages is the number of internal cut levels needed to extract all
 * items from the block:
 *   - 0: a single item with no internal cuts
 *   - 1: items arranged along a single axis (all cuts in first_cut_orientation)
 *   - k: items requiring k alternating levels of cuts
 *
 * first_cut_orientation is the direction of the outermost internal cut. It is
 * set to Vertical by convention when number_of_stages == 0.
 *
 * Combined blocks are defined recursively via parent_1_id and parent_2_id,
 * which are indices into the same bin type's block vector:
 *   - parent_1 is placed at (0, 0) relative to this block's origin
 *   - parent_2 is placed at (parent_1.rect.w, 0) when first_cut_orientation
 *     is Vertical, or at (0, parent_1.rect.h) when Horizontal
 *
 * Generated by compute_blocks(); placed in 3-cut sub-plates during tree search.
 */
struct Block
{
    /** Bounding rectangle of all items in the block. */
    Rectangle rect;

    /** Sum of areas of all items inside the block. */
    Area item_area = 0;

    /**
     * True iff this block is a uniform cx x cy grid of a single item type.
     * number_of_stages may be 0 (cx==cy==1), 1 (exactly one of cx,cy > 1), or
     * 2 (both cx > 1 and cy > 1).
     */
    bool is_simple = false;

    /** Item type id, valid only when is_simple == true. */
    ItemTypeId item_type_id = -1;

    /** Rotation of the item, valid only when is_simple == true. */
    bool rotate = false;

    /** Number of copies in the x direction, valid only when is_simple == true. */
    ItemPos copies_x = 1;

    /** Number of copies in the y direction, valid only when is_simple == true. */
    ItemPos copies_y = 1;

    /**
     * Number of copies of each item type used in this block, as a sorted
     * sparse list of (item_type_id, count) pairs.
     */
    std::vector<std::pair<ItemTypeId, ItemPos>> item_copies;

    ItemPos number_of_items = 0;

    /**
     * Number of internal cut levels required to extract items from this block.
     */
    Counter number_of_stages = 0;

    /**
     * Direction of the outermost internal guillotine cut. Irrelevant when
     * number_of_stages == 0; set to Vertical by convention in that case.
     */
    CutOrientation first_cut_orientation = CutOrientation::Vertical;

    /**
     * Indices of the two parent blocks within the same bin type's block vector.
     * -1 when is_simple == true.
     */
    ItemPos parent_1_id = -1;
    ItemPos parent_2_id = -1;

    double fill_rate() const { return (double)item_area / rect.area(); }
};

std::ostream& operator<<(std::ostream& os, const Block& block);

/**
 * Parameters for compute_blocks().
 */
struct BlockParameters
{
    /** Maximum number of blocks to generate per bin type. */
    ItemPos maximum_number_of_blocks = 10000;
};

/**
 * Generate guillotine blocks for each bin type of the given instance.
 *
 * Only generates blocks whose number_of_stages is at most
 * instance.parameters().number_of_stages - 3, so that placing the block in a
 * 3-cut sub-plate does not exceed the allowed total number of stages.
 *
 * Returns one vector of blocks per bin type (indexed by BinTypeId).
 */
std::vector<std::vector<Block>> compute_blocks(
        const Instance& instance,
        const BlockParameters& parameters = {});

}
}
