#pragma once

#include "packingsolver/rectangleguillotine/solution.hpp"
#include "rectangle/block.hpp"

namespace packingsolver
{
namespace rectangleguillotine
{

/**
 * A rectangleguillotine block: a rectangular envelope filled by items
 * according to an explicit guillotine cut tree.
 *
 * Unlike rectangle::Block (which only stores item positions), each Block
 * records the complete cut tree so that to_solution can drive SolutionBuilder
 * without re-deriving cut positions or directions.  This eliminates the
 * direction-fallback bug that arose when add_items inserted children at an
 * incorrect depth parity.
 *
 * Trim-waste nodes (item_type_id == -1, first_child < 0) are inserted
 * wherever items do not fill the full extent of a sub-region.
 *
 * Block dimensions and item positions assume cut_thickness == 0 within the
 * block; the branching scheme accounts for cut_thickness only between the
 * block and the surrounding empty spaces.
 */
struct Block
{
    /**
     * A node in the guillotine cut tree.
     *
     * Stored as a flat array in Block::nodes with nodes[0] as the root.
     * All coordinates are in block-local space (BL of block = origin).
     *
     * Leaf (first_child < 0): item (item_type_id >= 0) or waste (-1).
     * Internal: cut_is_vertical, cut_pos, first_child, second_child.
     *   first_child  = left child (vertical cut) or bottom child (horizontal).
     *   second_child = right child (vertical cut) or top child (horizontal).
     */
    struct Node {
        Length x0 = 0;
        Length y0 = 0;
        Length width = 0;
        Length height = 0;

        ItemTypeId item_type_id = -1;
        bool rotate = false;

        bool cut_is_vertical = false;
        Length cut_pos = 0;
        int first_child = -1;
        int second_child = -1;
    };

    /** Envelope dimensions (.x = width, .y = height). */
    rectangle::Rectangle rect = {0, 0};

    Area item_area = 0;
    Profit item_profit = 0;
    Weight weight = 0;
    ItemPos number_of_items = 0;

    std::vector<std::pair<ItemTypeId, ItemPos>> item_copies;

    std::vector<Node> nodes;

    double fill_rate() const
    {
        return (rect.x > 0 && rect.y > 0)?
            (double)item_area / ((Area)rect.x * rect.y):
            0.0;
    }
};

std::ostream& operator<<(std::ostream& os, const Block& block);

/**
 * Generate guillotine blocks for each bin type of the instance.
 *
 * Returns one vector of blocks per bin type (indexed by BinTypeId).
 * Internally converts each rectangle::Block (generated by
 * rectangle::compute_blocks) into a rectangleguillotine::Block by building
 * the explicit guillotine cut tree and inserting trim-waste nodes.
 */
std::vector<std::vector<Block>> compute_blocks(
        const Instance& instance,
        const rectangle::BlockParameters& parameters = {});

} // namespace rectangleguillotine
} // namespace packingsolver
