/**
 * This file was generated by bin2cpp v3.0.0
 * Copyright (C) 2013-2021 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'minlp_model.mod', last modified 1678639729.
 * Do not modify this file.
 */
#ifndef MINLP_MODEL_HPP
#define MINLP_MODEL_HPP

#include <stddef.h>

namespace packingsolver
{
  #ifndef PACKINGSOLVER_EMBEDDEDFILE_CLASS
  #define PACKINGSOLVER_EMBEDDEDFILE_CLASS
  class File
  {
  public:
    virtual size_t getSize() const = 0;
    /* DEPRECATED */ virtual inline const char * getFilename() const { return getFileName(); }
    virtual const char * getFileName() const = 0;
    virtual const char * getFilePath() const = 0;
    virtual const char * getBuffer() const = 0;
    virtual bool save(const char * filename) const = 0;
  };
  #endif //PACKINGSOLVER_EMBEDDEDFILE_CLASS
  const File & getMinlpModelFile();
}; //packingsolver

#endif //MINLP_MODEL_HPP
