#pragma once

#include "packingsolver/irregular/instance.hpp"

namespace packingsolver
{
namespace irregular
{

Shape clean_shape(const Shape& shape);

/**
 * Perfectly equalize equal y-values in order to reduce the number of trapezoids
 * generated by the trapezoidation.
 *
 * This step must be done right before the trapezoidation.
 */
Shape clean_shape_y(const Shape& shape);

}
}
