#pragma once

#include "packingsolver/box/solution.hpp"

namespace packingsolver
{
namespace box
{

/**
 * A block: a rectangular envelope filled with items in a guillotine pattern.
 *
 * Items are laid out relative to the block origin (0,0,0). The envelope is the
 * smallest axis-aligned box enclosing all items. fill_rate = allocated_volume /
 * box.volume().
 *
 * Generated by compute_blocks(); allocated in empty spaces during tree search.
 */
struct Block
{
    /** Envelope dimensions. */
    Box box;

    /** Sum of volumes of all items inside the block. */
    Volume allocated_volume = 0;

    /**
     * Number of copies of each item type used in this block, as a sorted
     * sparse list of (item_type_id, count) pairs.  Only item types with at
     * least one copy are present.
     */
    std::vector<std::pair<ItemTypeId, ItemPos>> item_copies;

    /**
     * Items with their positions relative to the block's bottom-left-back
     * corner (origin).  Uses SolutionItem::bl_corner as the relative position.
     */
    std::vector<SolutionItem> items;

    double fill_rate() const { return (double)allocated_volume / box.volume(); }
};

/**
 * Parameters for compute_blocks().
 */
struct BlockParameters
{
    /** Maximum number of blocks to generate (N_B in the thesis). */
    ItemPos maximum_number_of_blocks = 10000;

    /**
     * Minimum fill rate ε: blocks whose fill_rate < minimum_fill_rate are
     * discarded.  0.0 disables the check (accept all blocks).
     */
    double minimum_fill_rate = 0.0;
};

/**
 * Generate up to parameters.maximum_number_of_blocks guillotine blocks for
 * each bin type of the given instance.
 *
 * Returns one vector of blocks per bin type (indexed by BinTypeId).
 *
 * Implements Algorithm 3.5 (GENERATE-GUILLOTINE-BLOCKS) from:
 *   Lucas Guesser Targino da Silva, "A Tree Search-Based Heuristic for the
 *   Three-Dimensional Single Container Loading Problem", UNICAMP 2025.
 */
std::vector<std::vector<Block>> compute_blocks(
    const Instance& instance,
    const BlockParameters& parameters = {});

} // namespace box
} // namespace packingsolver
