#pragma once

#include "packingsolver/box/solution.hpp"

namespace packingsolver
{
namespace box
{

/**
 * A block: a rectangular envelope filled with items in a guillotine pattern.
 *
 * Items are laid out relative to the block origin (0,0,0). The envelope is the
 * smallest axis-aligned box enclosing all items. fill_rate = item_volume /
 * box.volume().
 *
 * Generated by compute_blocks(); allocated in empty spaces during tree search.
 */
struct Block
{
    /** Envelope dimensions (lifted: extended by max_reachable in each direction). */
    Box box;

    /** Sum of volumes of all items inside the block. */
    Volume item_volume = 0;

    bool is_simple = false;

    ItemTypeId item_type_id = -1;

    Rotation rotation;

    /**
     * Number of copies of each item type used in this block, as a sorted
     * sparse list of (item_type_id, count) pairs.  Only item types with at
     * least one copy are present.
     */
    std::vector<std::pair<ItemTypeId, ItemPos>> item_copies;

    /**
     * Items with their positions relative to the block's bottom-left-back
     * corner (origin).  Uses SolutionItem::bl_corner as the relative position.
     */
    std::vector<SolutionItem> items;

    ItemPos number_of_items = 0;

    double fill_rate() const { return (double)item_volume / box.volume(); }
};

std::ostream& operator<<(std::ostream& os, const Block& block);

/**
 * Per-axis reachable-length tables.
 *
 * max_reachable_x[r] = largest length ≤ r achievable by stacking copies of
 * items (one rotation per copy, respecting copy limits) along x.  Computed
 * once from the instance and shared by compute_blocks and
 * BranchingSchemeMaximalSpaces.
 */
struct MaxReachableLengths
{
    std::vector<Length> x;
    std::vector<Length> y;
    std::vector<Length> z;
};

MaxReachableLengths compute_max_reachable_lengths(const Instance& instance);

/**
 * Parameters for compute_blocks().
 */
struct BlockParameters
{
    /** Maximum number of blocks to generate (N_B in the thesis). */
    ItemPos maximum_number_of_blocks = 10000;
};

/**
 * Generate up to parameters.maximum_number_of_blocks guillotine blocks for
 * each bin type of the given instance.
 *
 * max_reachable_lengths is used to lift each returned block's declared box:
 *   block.box.x += max_reachable_lengths.x[bin.x - block.box.x]
 * and similarly for y and z.  This extends each block's footprint to the
 * maximum coverage achievable when the block is placed against the bin wall,
 * avoiding the creation of provably-unusable sub-spaces.
 *
 * Returns one vector of blocks per bin type (indexed by BinTypeId).
 */
std::vector<std::vector<Block>> compute_blocks(
    const Instance& instance,
    const BlockParameters& parameters = {});

} // namespace box
} // namespace packingsolver
