#include "packingsolver/onedimensional/instance_builder.hpp"

using namespace packingsolver;
using namespace packingsolver::onedimensional;

InstanceBuilder instance_builder;
instance_builder.set_objective(Objective::BinPacking);
BinTypeId bin_type_id = instance_builder.add_bin_type(1000);
instance_builder.set_bin_type_copies(bin_type_id, 100);
instance_builder.add_item_type(193);
instance_builder.add_item_type(197);
instance_builder.add_item_type(199);
instance_builder.add_item_type(211);
instance_builder.add_item_type(223);
instance_builder.add_item_type(227);
instance_builder.add_item_type(229);
instance_builder.add_item_type(233);
instance_builder.add_item_type(239);
instance_builder.add_item_type(241);
instance_builder.add_item_type(251);
instance_builder.add_item_type(257);
instance_builder.add_item_type(263);
instance_builder.add_item_type(269);
instance_builder.add_item_type(271);
instance_builder.add_item_type(277);
instance_builder.add_item_type(281);
instance_builder.add_item_type(283);
instance_builder.add_item_type(293);
instance_builder.add_item_type(307);
instance_builder.add_item_type(311);
instance_builder.add_item_type(313);
instance_builder.add_item_type(317);
instance_builder.add_item_type(331);
instance_builder.add_item_type(337);
instance_builder.add_item_type(347);
instance_builder.add_item_type(349);
instance_builder.add_item_type(353);
instance_builder.add_item_type(359);
instance_builder.add_item_type(367);
instance_builder.add_item_type(373);
instance_builder.add_item_type(379);
instance_builder.add_item_type(383);
instance_builder.add_item_type(389);
instance_builder.add_item_type(397);
instance_builder.add_item_type(401);
instance_builder.add_item_type(409);
instance_builder.add_item_type(419);
instance_builder.add_item_type(421);
instance_builder.add_item_type(431);
instance_builder.add_item_type(433);
instance_builder.add_item_type(439);
instance_builder.add_item_type(443);
instance_builder.add_item_type(449);
instance_builder.add_item_type(457);
instance_builder.add_item_type(461);
instance_builder.add_item_type(463);
instance_builder.add_item_type(467);
instance_builder.add_item_type(479);
instance_builder.add_item_type(487);
instance_builder.add_item_type(491);
instance_builder.add_item_type(499);
Instance instance = instance_builder.build();
