import packingsolver.rectangleguillotine as psg

instance_builder = psg.InstanceBuilder()
instance_builder.set_objective(psg.Objective.BinPackingWithLeftovers)
instance_builder.set_number_of_stages(3)
instance_builder.set_cut_type(psg.CutType.Homogenous)
instance_builder.set_first_stage_orientation(psg.CutOrientation.Vertical)
instance_builder.add_bin_type(80, 40, copies=7)
instance_builder.add_item_type(23, 23, oriented=True, copies=3)
instance_builder.add_item_type(19, 19, oriented=True, copies=3)
instance_builder.add_item_type(17, 17, oriented=True, copies=3)
instance_builder.add_item_type(13, 13, oriented=True, copies=3)
instance_builder.add_item_type(13, 4, oriented=True)
instance_builder.add_item_type(13, 10, oriented=True)
instance_builder.add_item_type(12, 20, oriented=True)
instance_builder.add_item_type(9, 11, oriented=True)
instance_builder.add_item_type(11, 11, oriented=True)
instance_builder.add_item_type(13, 11, oriented=True)
instance_builder.add_item_type(7, 7, oriented=True, copies=3)
instance_builder.add_item_type(5, 5, oriented=True, copies=3)
instance = instance_builder.build()
